services:
    pictures_db:
        image: bitnami/mongodb:7.0.14
        restart: always
        container_name: picturesDB
        environment:
            MONGODB_ROOT_USER: ${MONGO_ROOT_USERNAME}
            MONGODB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGODB_USERNAME: ${MONGO_USER_USERNAME}
            MONGODB_PASSWORD: ${MONGO_USER_PASSWORD}
            MONGODB_DATABASE: 'picturesDB'
        ports:
            - 27035:27017

    pictures_web:
        image: node:hydrogen-slim
        container_name: pictures
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - 3005:3000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
